config/routes.rb
Rails.application.routes.draw do
  resources :cars
  root 'cars#index'

end

app/models/car.rb
class Car < ActiveRecord::Base
  validates :manufacturer, presence: true
  validates :color, presence: true
  validates :year, presence: true, numericality: { greater_than_or_equal_to: 1920}
  validates :mileage, presence: true, numericality: true
  validates :description, length: {maximum: 500}
  validates :country, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController

  def index
    @cars = Car.all.order("created_at DESC").limit(10)
  end

  def new
    @car= Car.new
  end

  def create
    @car = Car.new(car_params)
    if @car.save
      flash[:notice] = "You've successfully listed your vehicle"
      redirect_to cars_path
    else
      flash[:notice] = "Your input has invalid information, try again"
      render :'new'
    end
  end

  private

  def car_params
    params.require(:car).permit(:manufacturer, :color, :year, :mileage, :description, :country)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cars/index.html.erb
<h3 class="text-center">Most recent used cars Listing</h3>
<%= link_to "List A Car", new_car_path, class: "btn-success btn-large" %>
<table class="table table-hover">
   <thead>
      <tr>
         <th>Manufacturer</th>
         <th>Country</th>
         <th>Color</th>
         <th>Year</th>
         <th>Mileage</th>
         <th>Description
      </tr>
   </thead>
   <tbody>
   <% @cars.each do |car| %>
      <tr>
         <td><%= car.manufacturer %></td>
         <td><%= car.country %></td>
         <td><%= car.color %></td>
         <td><%= car.year %></td>
         <td><%= car.mileage %></td>
         <td><%= car.description %></td>
      </tr>
   <% end%>
   </tbody>
</table>

app/views/cars/new.html.erb
<%= link_to "Back To List Of Cars", cars_path, class: "btn btn-large" %>
<h3>Fill out the form to register a new car entry</h3>
<%= bootstrap_form_for(@car) do |f| %>
  <%= f.text_field :country %>
  <%= f.text_field :manufacturer %>
  <%= f.text_field :color %>
  <%= f.text_field :year  %>
  <%= f.text_field :mileage %>
  <%= f.text_area :description %>
  <%= f.submit "Register" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>UsedCars</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% if notice %>
    <p class="alert alert-success"><%= notice %></p>
  <% end %>
  <% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
  <% end %>
  <div class="container">
  <%= yield %>
  </div>
</body>
</html>